'\" t
.\"     Title: setroot
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/13/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SETROOT" "1" "03/13/2016" "v2\&.0" "Setroot Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
setroot \- sets your wallpaper\&.
.SH "SYNOPSIS"
.sp
\fBsetroot\fR [\fIstorage flag\fR] [\fIglobal flag\fR] { [\fIimage flags, manipulations, options\fR] <filename> }+ [\fImonitor flag\fR]
.SH "DESCRIPTION"
.sp
\fBsetroot\fR is a lightweight Xinerama\-aware CLI background setter in the vein of imlibsetroot, hsetroot, and feh\&. Its only non\-obvious dependency is \fIimlib2\fR\&.
.SH "INVOCATION"
.sp
The order of the filenames determines which monitor the wallpaper is set to\&. The first invoked filename is set to the first Xinerama monitor; the second to the second; and so on\&.
.sp
If more than one image option is applied, the last one takes effect\&.
.sp
If \fIn\fR filenames are supplied for \fIk\fR monitors, where \fIn\fR > \fIk\fR, only the first \fIk\fR filenames will be processed\&.
.sp
An illegal invocation sequence will result in setroot terminating with exit status \fB1\fR\&.
.SH "STORAGE FLAGS"
.PP
\fB\-\-store\fR
.RS 4
creates an executable file ".setroot-restore" located in directory
"${XDG_CONFIG_HOME:-$HOME/.config}/setroot/\&.setroot\-restore"
.sp
If the directory path and/or file does not exist, it will be created (see section \fBFILES\fR)\&.
.RE
.PP
\fB\-\-restore\fR
.RS 4
looks for
"${XDG_CONFIG_HOME:-$HOME/.config}/setroot/\&.setroot\-restore"
and executes it in shell (restores your previously set wallpapers and options)
.RE
.SH "GLOBAL FLAGS"
.PP
\fB\-\-blank\-color\fR \fI#RRGGBB\fR
.RS 4
sets background color of blank walls, unless overriden by
\fI\-\-bg\-color\fR
option
.RE
.SH "IMAGE FLAGS"
.PP
\fB\-\-span\fR
.RS 4
have image span all screens (no cropping)\&.
.sp
If more than one image is specified, the later image will be spanned\&.
.sp
Note that this overrides the \fI\-\-on\fR option\&. Note also that further images that are set (in the case of multiple monitors) will "cover" the spanned image\&.
.RE
.PP
\fB\-\-bg\-color\fR \fI#RRGGBB\fR
.RS 4
set empty space around image to color
.RE
.PP
\fB\-\-on\fR \fIn\fR
.RS 4
assign image to be wallpaper on Xinerama monitor
\fIn\fR
.sp
If not all images are passed this option, the unassigned walls will be placed on monitors by their position in the invocation sequence\&.
.sp
Images which do have a specified assignment will then be assigned to their monitors, replacing any images which may have already been assigned\&.
.sp
If \fI\-\-on\fR is supplied a screen which does not exist, no error is raised and the other walls are set as normal\&. This can be used with \fBsetroot --store\fR to "preset" an unconnected monitor's wallpaper\&.
.sp
If \fBsetroot\fR was not compiled with Xinerama support then \fB--on\fR is considered an invalid command and the program will terminate will terminate with exit status 1. 
.RE
.SH "IMAGE MANIPULATIONS"
.PP
\fB\-\-blur\fR \fI<radius>\fR
.RS 4
blur image
.RE
.PP
\fB\-\-sharpen\fR \fI<radius>\fR
.RS 4
sharpen image
.RE
.PP
\fB\-\-brighten\fR \fI<amount>\fR
.RS 4
modify image brightness by amount (between \-1 and 1)
.RE
.PP
\fB\-\-contrast\fR \fI<amount>\fR
.RS 4
modify contrast of image by amount (between \-100 and 100)
.RE
.PP
\fB\-\-flip\fR[\fIhvd\fR]
.RS 4
flip image [\fIh\fR]orizontally, [\fIv\fR]ertically, or [\fId\fR]iagonally
.RE
.PP
\fB\-\-tint\fR \fI#RRGGBB\fR
.RS 4
tint image with color \fI#RRGGBB\fR (also accepts valid XColor)
.RE
.PP
\fB\-\-greyscale\fR
.RS 4
renders image as greyscale (uses luminosity algorithm)
.RE
.SH "IMAGE OPTIONS"
.PP
\fB\-c, \-\-center\fR
.RS 4
place unscaled image centered and cropped to screen
.RE
.PP
\fB\-t, \-\-tiled\fR
.RS 4
tile image on invoked screen (Xinerama aware)
.RE
.PP
\fB\-s, \-\-stretch\fR
.RS 4
stretch image (disregard aspect) on invoked screen
.RE
.PP
\fB\-z, \-\-zoom\fR
.RS 4
scale image (preserve aspect) to fit screen completely (could cut off image)
.RE
.PP
\fB\-f, \-\-fit\-auto\fR
.RS 4
scale image (preserve aspect) to fit screen (entire image on screen) \- default
.RE
.PP
\fB\-fh, \-\-fit\-height\fR
.RS 4
scale image (preserve aspect) until height matches invoked screen
.RE
.PP
\fB\-fw, \-\-fit\-width\fR
.RS 4
scale image (preserve aspect) until width matches invoked screen
.RE
.PP
\fB\-gx, \-\-gravity\-x\fB \fI<position>\fR
.RS 4
set the image gravity center in the X axis at \fIposition\fR (an integer absolute
position or a float percentage) - default: 50%
.RE
.PP
\fB\-gy, \-\-gravity\-y\fB \fI<position>\fR
.RS 4
set the image gravity center in the Y axis at \fIposition\fR (an integer absolute
position or a float percentage) - default: 50%
.RE
.PP
\fB\-sc, \-\-solid\-color\fB \fI#RRGGBB\fR
.RS 4
set background to solid color \fI#RRGGBB\fR (hex code, also accepts valid XColor)
.RE
.SH "MONITOR FLAGS"
.PP
\fB\-\-use\-x\-geometry\fR
.RS 4
number Xinerama monitors from leftmost to rightmost
.RE
.PP
\fB\-\-use\-y\-geometry\fR
.RS 4
number Xinerama monitors from topmost to bottommost
.RE
.SH "GRAVITY"
.sp
When the \fI\-z\fR option is used, the image is zoomed in to fill the screen
and cropped if neccessary. The \fI\-\-gravity\-x\fR and \fI\-\-gravity\-y\fR
parameters let you choose the 'gravity center' of the image: \fBsetroot\fR will try
to match that center with the display center if possible.
.sp
Both parameters can be given in two formats, both relative to the image
dimensions: as an integer, which means an absolute coordinate; or as a
decimal percentage of the total width or height.
.SH "FILES"
.sp
\fBsetroot\fR creates the directory "${XDG_CONFIG_HOME:-$HOME/.config}/setroot" and places an executable file \fB.setroot-restore\fR there when \fBsetroot --store\fR is invoked for the first time\&.
.sp
\fBsetroot --restore\fR uses this file to restore the most recent (valid) invocation of \fBsetroot\fR\&.
.SH "AUTHOR"
.sp
\fB\(co 2016\fR Tim Zhou <ttzhou@uwaterloo\&.ca>
.SH "ACKNOWLEDGMENTS"
.sp
\fIset_pixmap_property()\fR is \fB\(co 1998\fR Michael Jennings <mej@eterm\&.org>
.sp
\fIfind_desktop()\fR is a modification of get_desktop_window() \fB\(co 2004\-2012\fR Jonathan Koren <jonathan@jonathankoren\&.com>
