CHANGELOG
=========

Release
-------

v1.4.2
------

- fixed bugs (very, very rare) caused by hash marks in cli arguments when re/storing
- `setroot` now adds a backslash to escape the hash marks in `.setroot-restore`
- currently does not escape backslashes on their own... if anyone complains i'll add it :)

v1.4.1
------

- code base changes
- added error handling cases for --store and --on

v1.4
----

- handle spaces, special characters, allows you to set wallpaper in advance for unconnected monitors
- making libxinerama an optional dependency

v1.3
----

- autocreates the appropriate config directory

v1.2
----

- _--store_ and _--restore_ now use _$\{XDG_CONFIG_DIR:-$HOME/.config\}_

v1.1
----

- added _greyscale_ option

v1.0
----

- added manpage, PKGBUILD
- code cleanup
- awaiting feature requests


Pre-Release
-----------

v0.95
-----

- added ability to specifiy monitor arrangement (see README)

v0.9
----

- added ability to assign a wall to a monitor by number

v0.8
----

- restructured code to be simpler

v0.7
----

- clamped a bunch of bugs and headaches
- stable, but am planning to add ability to specify monitor before moving to v1.0

v0.6
----

- added image manipulation option brightness and contrast
- added ability to specify bg color of blank walls

v0.5
----

- added image manipulation option tint
- fixed some more bugs with memory
- moved `show_help()` and `show_ver()` to another file

v0.4
----

- added image manipulation options flip, sharpen, blur
- fixed some more bugs

v0.3
----

- fixed bugs introduced by new algorithms
- made program easier to refactor

v0.2
----

- revamped the sizing algorithms, much faster now, cutting down SLOC
- started version numbering :)

v0.1
----

- Initial alpha
